#ifndef _CONFIGURATION_HEADER_GUARD_H_
#define _CONFIGURATION_HEADER_GUARD_H_

#define HAVE_LZ4 TRUE
/* #undef HAVE_SNAPPY */
#define HAVE_ZLIB TRUE
#undef HAVE_ZSTD 
/* #undef BLOSC_DLL_EXPORT */


#endif
